/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

/*

to run

java -cp "C:\Users\yujiang\work\java\DetectQrCode\app\build\libs\app.jar;C:\Users\yujiang\work\java\boofcv-v1.2.0-libs\boofcv-v1.2.0-libs\*" org.example.App


*/

import boofcv.abst.fiducial.QrCodeDetector;
import boofcv.alg.fiducial.qrcode.QrCode;
import boofcv.factory.fiducial.ConfigQrCode;
import boofcv.factory.fiducial.FactoryFiducial;
import boofcv.gui.feature.VisualizeShapes;
import boofcv.gui.image.ShowImages;
import boofcv.io.UtilIO;
import boofcv.io.image.ConvertBufferedImage;
import boofcv.io.image.UtilImageIO;
import boofcv.struct.image.GrayU8;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.List;

/**
 * Shows you how to detect a QR Code inside an image and process the extracted data. Much of the information that
 * is computed while detecting and decoding a QR Code is saved inside the {@link QrCode} class. This can be useful
 * for application developers.
 *
 * @author Peter Abeles
 */
public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
	public static void main( String[] args ) {

        if (args.length <= 0) {
            System.out.println("Usage: java -cp \"<jar-file>;<boofcv-libs>\" org.example.App <image-path>");
            return;
        }

		//BufferedImage input = UtilImageIO.loadImageNotNull(UtilIO.pathExample("C:\\Users\\yujiang\\work\\go\\src\\qrvideo\\\\bad0.jpg"));
        BufferedImage input = UtilImageIO.loadImageNotNull(UtilIO.pathExample(args[0]));
		GrayU8 gray = ConvertBufferedImage.convertFrom(input, (GrayU8)null);

		var config = new ConfigQrCode();
//		config.considerTransposed = false; // by default, it will consider incorrectly encoded markers. Faster if false
		QrCodeDetector<GrayU8> detector = FactoryFiducial.qrcode(config, GrayU8.class);

		detector.process(gray);

		// Gets a list of all the qr codes it could successfully detect and decode
		List<QrCode> detections = detector.getDetections();

		Graphics2D g2 = input.createGraphics();
		int strokeWidth = Math.max(4, input.getWidth()/200); // in large images the line can be too thin
		g2.setColor(Color.GREEN);
		g2.setStroke(new BasicStroke(strokeWidth));
		for (QrCode qr : detections) {
			// The message encoded in the marker
			System.out.print(qr.message);

			// Visualize its location in the image
			//VisualizeShapes.drawPolygon(qr.bounds, true, 1, g2);
		}

		// List of objects it thinks might be a QR Code but failed for various reasons
		List<QrCode> failures = detector.getFailures();
		g2.setColor(Color.RED);
		for (QrCode qr : failures) {
			// If the 'cause' is ERROR_CORRECTION or higher, then there's a decent chance it's a real marker
			if (qr.failureCause.ordinal() < QrCode.Failure.ERROR_CORRECTION.ordinal())
				continue;

			//VisualizeShapes.drawPolygon(qr.bounds, true, 1, g2);
		}

		//ShowImages.showWindow(input, "Example QR Codes", true);
	}
}